config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#index'
  get 'changelog', to: 'home#changelog'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations'
  }

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  namespace :users do
    resources :settings, only: [] do
      collection do
        get 'password/edit', to: 'settings#edit_password'
        put 'password'
      end
    end
  end

  resources :posts, only: %i[new show edit create update destroy] do
    resources :comments, only: %i[create]

    resources :posters, only: %i[new] do
      collection do
        get :show
      end
    end

    collection do
      get :autocomplete
      get :lost
      get :found
      get :category_selects

      get :search
    end
  end

  resources :places do
    collection do
      get :search
    end
  end

  resources :notifications, only: %i[index]
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  before_action :set_filter, only: [:index]
  before_action :set_tab, only: [:index]

  def index
    @search = params[:q][:name_cont] if params[:q]
    @q = @tab == 'all_posts' ? Post.ransack(params[:q]) : current_user.posts.ransack(params[:q])
    @posts = @q.result

    @losts = load_posts_with_filter(:lost_item)
    @founds = load_posts_with_filter(:found_item)
  end

  private

  def set_tab
    @tab = params[:tab] || 'all_posts'
  end

  def set_filter
    @filter = params[:filter] || {}
  end

  def load_posts_with_filter(category)
    status = @filter.dig(category, :status)
    posts = status.present? ? @posts.send(status.to_sym) : @posts
    posts.where(category:).latest.limit(4)
  end
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/views/home/_filter.html.erb
<div data-controller="my-posts">
  <%= f.hidden_field "filter[#{category}][status]", value: filter.dig(category.to_sym, :status),
    data: { 'my-posts-target': 'statusInput' } %>

  <div class="form-check-inline" id="active-checkbox">
    <label class="t">
      <%= check_box_tag '', 'active', filter.dig(category.to_sym, :status) == 'active', {
        data: {
          action: 'input->my-posts#checkboxChange',
          my_posts_target: "activeCheckbox"
        }
      } %> กำลังตามหา
    </label>
  </div>
  <div class="form-check-inline" id="in-active-checkbox">
    <label class="t">
      <%= check_box_tag '', 'in_active', filter.dig(category.to_sym, :status) == 'in_active', {
        data: {
          action: 'input->my-posts#checkboxChange',
          my_posts_target: "inActiveCheckbox"
        }
      } %> ปิดโพสต์
    </label>
  </div>
</div>

app/views/home/_post_content.html.erb
<%
  q = @search.present? ? { name_cont: "#{@search}" } : nil

  if category == 'lost_item'
    link_posts = lost_posts_path(q:, tab:, filter: { lost_item: { status: filter.dig(:lost_item, :status) } })
    header = 'โพสต์ตามหาของหาย'
    date_label = 'วันที่หาย'
    location_label = 'สถานที่หาย'
  end

  if category == 'found_item'
    link_posts = found_posts_path(q:, tab:, filter: { found_item: { status: filter.dig(:found_item, :status) } })
    header = 'โพสต์ตามหาเจ้าของ'
    date_label = 'วันที่พบ'
    location_label = 'สถานที่เจอ'
  end

%>
<div class="container">
  <div class="row mt-5" id="post-content-<%= category %>">
    <h4 class="col-auto order-1"><%= header %></h4>
    <div class="col-md-5 order-3 order-md-2">
      <% if tab == 'my_post' %>
        <%= render 'filter', f:, filter:, category: %>
      <% end %>
      </div>
      <div class="col order-2 order-md-3 d-md-flex justify-content-end align-items-center" style="margin-bottom: 1rem; margin-left: 1rem;" id="button-all-post-<%= category %>">
        <%= link_to('ดูรายการทั้งหมด', link_posts, class: 'font-weight500 me-2') %><i class="fa-solid fa-angles-right"></i>
      </div>
    </div><br>
    <% if posts.present? %>
      <div class="row">
        <% posts.each do |post| %>
          <div class="col-md-6 col-lg-3 grid mb-5">
            <article>
              <% if post.images.attached? %>
                  <%= image_tag(post.images[0]) %>
              <% else %>
                  <%= image_tag 'no-image-available.png', alt: 'image'%>
              <% end %>
              <div class="text">
                <div class="post-name font-weight700"><%= post.name %></div>
                <div class="post-date">
                  <%= date_label %> : <span data-controller="datetime" data-datetime-date-value="<%= post.date %>" data-datetime-format-value='DD/MM/YYYY' data-datetime-target="output"></span>
                </div>
                <div class="post-location font-weight500"><i class="fa-solid fa-location-dot"></i> <%= post.location %></div>
                <% if post.active? %>
                  <div class="post-status-active">
                    <div class="circle-green"></div>
                    <p class="mb-0 ms-3 text-small font-weight600">กำลังตามหา</p>
                  </div>
                <% else %>
                  <div class="post-status-inactive">
                    <p class="text-small font-weight600 mb-0">ปิดโพสต์</p>
                  </div>
                <% end %>
                <div class="fst-italic text-small color--secondary300">โพสต์เมื่อวันที่ : <span data-controller="datetime" data-datetime-date-value="<%= post.created_at %>" data-datetime-format-value='DD/MM/YYYY' data-datetime-target="output"></span></div>
                <div class="d-grid" id="detail-post">
                  <%= link_to "ดูรายละเอียด", post_path(post), class: "see-other-btn btn btn--outline-secondary" %>
                </div>
              </div>
            </article>
          </div>
        <% end %>
      </div>
    <% else %>
      <div class="empty-result">
        <div class="bell-item">
          <i class="fa-regular fa-bell-on"></i>
          <p class="text-result">ไม่มีรายการแสดง</p>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/home/changelog.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <p class="text-header2">Changelog</p>
    </div>
  </div>

  <div class="row layout-03">
    <div class="col-md-12">
      <p class="text-subtitle">Version 1.1.3 - 19 October 2022</p>
      <ul>
        <li>Fixed: Re-send confirm email menu was gone from login page.</li>
      </ul>
    </div>
  </div>

  <div class="row layout-03">
    <div class="col-md-12">
      <p class="text-subtitle">Version 1.1.2 - 7 October 2022</p>
      <ul>
        <li>Fixed: Bugs tooltips in advance search.</li>
      </ul>
    </div>
  </div>

  <div class="row layout-03">
    <div class="col-md-12">
      <p class="text-subtitle">Version 1.1.1 - 6 October 2022</p>
      <ul>
        <li>Fixed: Layout on Preview Post page.</li>
        <li>Fixed: Bugs tooltips when reset password.</li>
      </ul>
    </div>
  </div>

  <div class="row layout-03">
    <div class="col-md-12">
      <p class="text-subtitle">Version 1.1.0 - 6 October 2022</p>
      <ul>
        <li>Update: Disable Google OAuth feature.</li>
        <li>Fixed: Bugs on Create Post menu.</li>
        <li>Fixed: Bugs on Responsive UI.</li>
      </ul>
    </div>
  </div>

  <div class="row layout-03">
    <div class="col-md-12">
      <p class="text-subtitle">Version 1.0.3 - 28 September 2022</p>
      <ul>
        <li>Update: Add auto scroll in post lists page.</li>
        <li>Fixed: Bugs on Advance Search menu.</li>
        <li>Fixed: Bugs on Responsive UI.</li>
      </ul>
    </div>
  </div>

  <div class="row layout-03">
    <div class="col-md-12">
      <p class="text-subtitle">Version 1.0.2 - 19 September 2022</p>
      <ul>
        <li>New: Feature Advance search post.</li>
        <li>Fixed: Make username to be unique field.</li>
        <li>Fixed: Bugs on close post modal.</li>
        <li>Fixed: Bugs when reset password token is invalid.</li>
      </ul>
    </div>
  </div>

  <div class="row layout-03">
    <div class="col-md-12">
      <p class="text-subtitle">Version 1.0.1 - 5 September 2022</p>
      <ul>
        <li>Update: User cannot use Thai character to setup password.</li>
        <li>Fixed: Add warning message when username duplicate with another user.</li>
        <li>Fixed: Responsive UI of Notification menu.</li>
      </ul>
    </div>
  </div>

  <div class="row layout-03">
    <div class="col-md-12">
      <p class="text-subtitle">Version 1.0.0 - 1 September 2022</p>
      <ul>
        <li>New: Landing page and Posts list menu.</li>
        <li>New: Feature Post management - Create, Update, Delete post.</li>
        <li>New: Feature Share post to facebook.</li>
        <li>New: Feature Create poster of post.</li>
        <li>New: Feature Comment & Reply in post detail page.</li>
        <li>New: Feature Notification when users comment on your post.</li>
        <li>New: Feature Search Post by post name, post detail.</li>
        <li>New: Feature User profile management.</li>
        <li>New: Feature Authentication - Login, Register, Forgot password, Change password.</li>
      </ul>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<%= render 'posts/search_form' %>

<div class="landing-listposts mt-14">
  <div class="container pt-5">
    <% if !user_signed_in? && (!params[:q].present? || !params[:q][:name_cont].present?) %>
      <div class="row justify-content-end align-items-center mb-5">
        <div class="col-md-auto order-md-last mb-5 mb-md-0">
          <a href="<%= category_selects_posts_path %>" id="button-create-post" style="text-decoration: none;">
            <div class="btn-fixed--bottom btn-size--md btn--primary btn--w-100 d-flex align-items-center justify-content-center" >
              <i class='fas fa-plus-circle'></i>&nbsp
              <span class="text">สร้างโพสต์</span>
            </div>
          </a>
        </div>
      </div>
    <% end %>
    <% if params[:q].present? && params[:q][:name_cont].present? %>
      <div class="row justify-content-start align-items-center">
        <div class="col">
          <div class="text-result-search">ผลลัพธ์การค้นหา
            <p>(<%= @posts.count %> รายการ)</p>
          </div>
          <hr class="m-0">
          <div class="search-value">
            <p class="text-body font-weight600">ค้นหา :</p>
            <div class="result-tag bg-color--primary200"> <%= params[:q][:name_cont] %></div>
          </div>
        </div>
      </div>
    <% end %>
    <% if user_signed_in? && (!params[:q].present? || !params[:q][:name_cont].present?) %>
      <div class="row justify-content-between align-items-center mb-5">
        <div class="col-md-auto order-md-last mb-5 mb-md-0">
          <a href="<%= category_selects_posts_path %>" id="button-create-post" style="text-decoration: none;">
            <div class="btn-fixed--bottom btn-size--md btn--primary btn--w-100 d-flex align-items-center justify-content-center" >
              <i class='fas fa-plus-circle'></i>&nbsp
              <span class="text">สร้างโพสต์</span>
            </div>
          </a>
        </div>
        <div class="col-md-5">
          <ul class="tabs mb-0" id="tabs-home-index">
            <% if @tab == 'my_post' %>
              <li class="tab-item" id="tab-all-post">
                <%= link_to 'รายการทั้งหมด', root_path , class: "btn btn--outline-secondary-tab tab-link" %>
              </li>
              <li class="tab-item" id="tab-my-post">
                <%= link_to 'รายการของฉัน', root_path(tab: 'my_post'), class: "btn btn--secondary-tab tab-link" %>
              </li>
            <% else %>
              <li class="tab-item" id="tab-all-post">
                <%= link_to 'รายการทั้งหมด', root_path, class: "btn btn--secondary-tab tab-link" %>
              </li>
              <li class="tab-item" id="tab-my-post">
                <%= link_to 'รายการของฉัน', root_path(tab: 'my_post'), class: "btn btn--outline-secondary-tab tab-link" %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    <% end %>
    <%= form_with(url: root_path, method: :get, id: 'homeFilter') do |f| %>
      <%= hidden_field_tag 'tab', @tab %>
      <%= render 'post_content', posts: @losts, category: 'lost_item', tab: @tab, filter: @filter, f: %>
      <br><br><hr class="style"><br>
      <%= render 'post_content', posts: @founds, category: 'found_item', tab: @tab, filter: @filter, f: %>
      <br><br><br>
    <% end %>
  </div>
</div>