config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#index'
  get 'changelog', to: 'home#changelog'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations'
  }

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  namespace :users do
    resources :settings, only: [] do
      collection do
        get 'password/edit', to: 'settings#edit_password'
        put 'password'
      end
    end
  end

  resources :posts, only: %i[new show edit create update destroy] do
    resources :comments, only: %i[create]

    resources :posters, only: %i[new] do
      collection do
        get :show
      end
    end

    collection do
      get :autocomplete
      get :lost
      get :found
      get :category_selects

      get :search
    end
  end

  resources :places do
    collection do
      get :search
    end
  end

  resources :notifications, only: %i[index]
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  enum category: { found_item: 0, lost_item: 1 }
  enum status: { active: 0, found: 1, closed: 2 }

  belongs_to :user
  belongs_to :type

  has_many :comments, dependent: :destroy

  has_many_attached :images, dependent: :destroy

  validates :name, presence: true
  validates :date, presence: true
  validate  :date_should_not_exceed_present
  validates :type_id, presence: true
  validates :detail, length: { maximum: 500 }, allow_blank: true

  validates :lat, numericality: true
  validates :lng, numericality: true

  scope :in_active, -> { where(status: %w[found closed]) }

  validates :images,
            presence: true,
            attached: true,
            content_type: { in: %w[image/jpeg image/png], message: 'must be jpeg or png.' },
            limit: { max: 10, message: 'over limited(10 files)' }

  attr_accessor :remove_images

  after_save :purge_images, if: :remove_images

  rails_admin do
    include_all_fields
    exclude_fields :type
    field :type_id, :enum do
      enum do
        Type.all.collect { |l| [l.type_name, l.id] }
      end
    end
    edit do
      field :images, :multiple_active_storage do
        delete_method :remove_images
      end
    end
  end

  def purge_images
    Array(remove_images).each do |id|
      ActiveStorage::Attachment.find_by(id:).try(:purge)
    end
  end

  def self.order_nearest(lat, lng)
    sql = sanitize_sql_array(
      [
        '((posts.lat - :lat) * (posts.lat - :lat)) + ((posts.lng - :lng) * (posts.lng - :lng)) ASC',
        { lat:, lng: }
      ]
    )
    order(Arel.sql(sql))
  end

  def owner?(user)
    user_id == user.id
  end

  def date_should_not_exceed_present
    return if date.blank?

    errors.add(:date, 'must not exceed present date') if date > Time.zone.today
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :set_tab, only: %i[lost found]
  before_action :set_filter, only: %i[lost found]
  before_action :load_posts, only: %i[lost found]
  before_action :load_post, only: %i[show edit update destroy]
  before_action :load_comments, only: %i[show]
  before_action :load_user, only: %i[show]
  before_action :mark_all_comments_as_read, only: %i[show]
  before_action :authorize_owner, only: %i[edit update]

  def show
    @https = 'https://www.'
    @fblink = 'facebook.com'
  end

  def new
    @post = Post.new(category: params[:category])
  end

  def edit; end

  def category_selects; end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to root_url
    else
      render :new, status: :unprocessable_entity, layout: 'nav_white'
    end
  end

  def update
    if @post.update(post_params)
      redirect_to post_path(@post.id)
    else
      render :edit, status: :unprocessable_entity, layout: 'nav_white'
    end
  end

  def destroy
    @post.destroy!
    redirect_to root_url, status: :see_other
  end

  def search
    @location = params[:location]
    @q = Post.ransack(params[:q])
    @posts = @q.result
    @posts = sort_by_coordinates

    @posts = @posts.page(params[:page]).per(8)
  end

  def autocomplete
    @search_results = Post.all.distinct.where('name ILIKE ?', "%#{params[:q]}%").pluck(:name)
    render layout: false
  end

  def lost
    @posts = load_posts_with_filter(:lost_item)
  end

  def found
    @posts = load_posts_with_filter(:found_item)
  end

  private

  def load_post
    if Post.find_by(id: params[:id]).present?
      @post = Post.find_by(id: params[:id])
    else
      render 'errors/not_found', status: :not_found
    end
  end

  def load_posts
    @search = params[:q][:name_cont] if params[:q]
    @q = @tab == 'all_posts' ? Post.ransack(params[:q]) : current_user.posts.ransack(params[:q])
    @posts = @q.result
  end

  def load_comments
    @comments = @post.comments.order(created_at: :asc)
  end

  def load_user
    @user = @post.user
  end

  def mark_all_comments_as_read
    return if @user != current_user

    notification_ids = @comments.map { |c| c.notifications_as_comment.ids }.flatten
    Notification.where(id: notification_ids).mark_as_read!
  end

  def set_tab
    @tab = params[:tab] || 'all_posts'
  end

  def set_filter
    @filter = params[:filter] || {}
  end

  def load_posts_with_filter(category)
    status = @filter.dig(category, :status)
    posts = status.present? ? @posts.send(status.to_sym) : @posts
    posts.where(category:).latest.page(params[:page]).per(12)
  end

  def sort_by_coordinates
    @lat = params[:lat]
    @lng = params[:lng]

    @posts.order_nearest(@lat, @lng)
  end

  def authorize_owner
    redirect_to post_path unless @post.owner?(current_user)
  end

  def post_params
    params.require(:post).permit(
      :name, :category, :status, :date, :time,
      :location, :detail, :reward, :lat, :lng,
      :type_id, :reason, images: [], remove_images: []
    )
  end
end

app/helpers/post_helper.rb
# frozen_string_literal: true

module PostHelper
  def self.item_detail(data)
    {
      id: data.id,
      location: data.location,
      lat: data.lat,
      lng: data.lng,
      title: data.name,
      path: Rails.application.routes.url_helpers.post_path(data),
      category: data.category.camelize(:lower)
    }.to_json
  end
end

app/views/posts/_form.html.erb
<%= simple_form_for post, {
  data: {
    controller: 'maps post-preview live-validate',
    post_preview_target: 'form',
    action: 'submit->post-preview#preview'
  }} do |f| %>

  <%= f.hidden_field :status, value: 'active', id: 'form-status-hidden-field' %>
  <%= f.hidden_field :category, data: { post_preview_target: 'categoryInput' }, id: 'form-category-hidden-field' %>
  <%= f.hidden_field :lat, data: { maps_target: "latitude", post_preview_target: "latitude", live_validate_target: 'latitude' }, id: 'form-latitude-hidden-field' %>
  <%= f.hidden_field :lng, data: { maps_target: "longitude", post_preview_target: "longitude", live_validate_target: 'longitude' }, id: 'form-longitude-hidden-field' %>
  <%= f.hidden_field :location, data: { maps_target: "address", post_preview_target: "address", live_validate_target: 'address' }, id: 'form-location-hidden-field' %>

  <div class="col-sm-9">
    <%= f.label "หัวข้อโพสต์", class: 'text-bold mb-3', id: 'form-name-label' %>
    <%= f.input :name, input_html: { data: { post_preview_target: 'nameInput', live_validate_target: 'name', action: "input->live-validate#checkName" }, id: 'post-name-input' }, error: "กรุณากรอกข้อมูล" , label: false %>
  </div>

  <br/>
  <div class="row g-5 ">
    <div class="col-md-6 col-lg-3">
      <%= f.label "ประเภท", class: 'text-bold mb-3' %>
      <%= f.input :type_id, label: false, :collection => Type.all.map{ |l| [l.type_name, l.id] }, error: "กรุณาเลือกประเภท", include_blank: 'เลือก',
        input_html: { data: {
          live_validate_target: 'types',
          action: "input->live-validate#checkTypes",
          post_preview_target: 'typeInput'
          }, id: 'post-types-input',
          class: 'form-select cursor-pointer' } %>
    </div>
    <div class="col-md-6 col-lg-3">
      <% if post.category == 'lost_item' %>
        <%= f.label "วันที่หาย", class: 'text-bold mb-3', id: 'form-lost-date-label' %>
      <% elsif post.category == 'found_item' %>
        <%= f.label "วันที่พบ", class: 'text-bold mb-3', id: 'form-found-date-label' %>
      <% end %>
      <%= f.input :date, as: :date, html5: true, input_html: { max: Date.today, data: { post_preview_target: 'dateInput', live_validate_target: 'date', action: "input->live-validate#checkDate" }, id: 'post-date-input' }, error: false, label: false%>
      <% if post.errors.key?(:date) %>
        <% if post.errors[:date] == ["can't be blank"] %>
          <p class="text-small text-danger pt-1" id="form-date-warning-text">กรุณาเลือกวันที่</p>
        <% end %>
        <% if post.errors[:date] == ["must not exceed present date"] %>
          <p class="text-small text-danger pt-1" id="form-date-warning-text">ไม่ควรเลือกวันที่เกินปัจจุบัน</p>
        <% end %>
      <% end %>
    </div>
  </div>
  <br>
  <div class="upload-title">
    <%= f.label :images, "อัปโหลดรูป*", class: 'text-bold', id: 'form-image-condition-label' %>
    <span class="text--gray"> (ต้องมีอย่างน้อย 1 รูป และสามารถอัพโหลดได้สูงสุดไม่เกิน 10 รูป)</span>
  </div>
  <div class="box dropzone dropzone-box <%= 'form-invalid' if post.errors.key?(:images) %>" id="dropzone-container" >
    <div class="dropzone dropzone-custom dz-clickable" id="dropzone" data-controller="dropzone" data-action = "click->live-validate#checkImages">
      <%= f.file_field :images, multiple: true, direct_upload: true, data: { dropzone_target: 'input'}, id: 'post-image-input' %>
      <div class="dropzone-msg dz-message ">
        <h3 class="plus"><i class="fa fa-plus"></i></h3>
      </div>
    </div>

    <% if post.images.attached? %>
      <% post.images.each do |image| %>
        <div class="d-inline" data-controller="remove-image">
          <div class="edit-upload text-center" data-controller="post-image" data-post-image-target="image">
            <%= f.hidden_field :images, multiple: true, value: image.signed_id, id: 'form-image-hidden-field' if !post.persisted? %>
            <div class="edit-image">
              <%= image_tag(image, id: 'form-image-display')%>
            </div>
            <%= f.label "remove file", type: 'submit', data: { action: 'click->live-validate#checkCountImages click->remove-image#clickCheckbox click->post-image#removeImage' }, class: 'edit-remove', id: "delete-image-button" %>
          </div>
          <%= check_box_tag 'post[remove_images][]', image.id, nil, data: { remove_image_target: 'checkbox'}, class: 'd-none', id: 'post_remove_images' %>
        </div>
      <% end %>
    <% end %>
  </div>
  <% if post.errors.key?(:images) %>
    <% if post.errors[:images] == ["can't be blank"] %>
      <p class="text-small text-danger pt-1" id="form-image-warning-text">กรุณาอัพโหลดรูป</p>
    <% end %>
    <% if post.errors[:images] == ["over limited(10 files)"] %>
      <p class="text-small text-danger pt-1" id="form-image-over-limit-warning-text">สามารถอัพโหลดได้สูงสุดไม่เกิน 10 รูป</p>
    <% end %>
  <% end %>
  <div class="col-sm-9">
    <%= f.label :detail, "รายละเอียดเพิ่มเติม", class: 'form-label mt-5 text-bold mb-3', id: 'form-deatil-label' %>
    <span class="text--gray"> (สามารถใส่ข้อความได้สูงสุดไม่เกิน 500 ตัวอักษร)</span>
    <%= f.input :detail, as: :text, error: false, input_html: { :rows => 7 , :style => 'height: 100%',
      data: {detail_length_target: "detail", controller: 'detail-length', post_preview_target: 'detailInput', live_validate_target: 'detail', action: 'input->live-validate#checkDetail input->detail-length#checkLength' }, id: 'post-detail-input' },
      label: false %>
    <p class="text-small text-danger d-none" id="form-detail-warning-text">สามารถใส่ข้อความได้สูงสุดไม่เกิน 500 ตัวอักษร</p>
  </div>
  <br>
  <div class="mt-3">
    <% if post.category == 'lost_item' %>
      <%= f.label "สถานที่หาย", class: 'text-bold mb-3', id: 'form-lost-location-label' %>
    <% elsif post.category == 'found_item' %>
      <%= f.label "สถานที่พบ", class: 'text-bold mb-3', id: 'form-found-location-label' %>
    <% end %>
  </div>

  <div class="form-group mb-3">
    <%= f.input :search, placeholder: "Search", required: true,
    input_html: {
      data: {
        maps_target: "field",
        live_validate_target: 'place',
        action: "keydown->maps#preventSubmit input->live-validate#checkPlace input->live-validate#checkLocationField input->maps#removeMarker"
      }, id: 'form-place-input', value: post.location, class: post.errors.key?(:lat) || post.errors.key?(:lng) ? 'form-invalid location' : 'form-control location' }, label: false %>
    <i class="fa fa-search form-control-feedback location"></i>

    <% if post.errors.key?(:lat) || post.errors.key?(:lng) %>
      <p class="text-small text-danger" id="form-place-warning-text">กรุณากรอกข้อมูล</p>
    <% end %>
  </div>
  <br>
  <div class="col-sm-10">
    <%= content_tag :div, nil, data: { maps_target: "map", live_validate_target: 'place', action: 'google-maps-callback@window->maps#initializeMap click->live-validate#checkPlace' }, class: 'map map-size mb-5', id: 'form-map-display' %>
  </div>
  <hr>
  <div class="d-grid gap-2 d-md-flex justify-content-md-end layout-05">
    <% if post.persisted? %>
      <%= link_to post, type: "reset", class: "btn-size--md btn--outline-secondary me-md-3", id: 'cancel-edit-form-button'  do %>
        ยกเลิก
      <% end %>
      <%= f.submit "บันทึก", class: "btn-size--md btn--primary", id: 'save-form-button' %>
    <% else %>
      <%= link_to category_selects_posts_path, type: "reset", class: "btn-size--md btn--outline-secondary me-md-3", id: 'cancel-create-form-button'  do %>
        ยกเลิก
      <% end %>
      <%= f.button :button, "สร้างโพสต์", type: 'submit', class: "btn-size--md btn--primary",
        data: {controller: 'delay-redirect', action: "click->delay-redirect#link"},
        id:"create-form-button" %>
      <%= render 'preview_modal', post: %>
    <% end %>
  </div>
<% end %>

app/views/posts/_item.html.erb
<div class="scroll">
  <% posts.each do |post| %>
    <div class = "box mb-5">
      <div id = "imm">
        <% if post.images.attached? %>
          <% post.images.each do |pic| %>
            <%= image_tag(pic, style:"width: 150px; height: 150px; object-fit: cover; ") %>
          <% end %>
        <% end %>
      </div>

      <div id = "namee">
        <strong>Name:</strong>
        <%= post.name %>
      </div>

      <div id = "datee">
        <strong>Date:</strong>
        <%= post.date %>
      </div>

      <div id = "locc">
        <strong>Location:</strong>
        <%= post.location %>
      </div>

      <div id = "linkk">
        <%= link_to "View Post >", post,style:"color: black; text-decoration: none;" %>
      </div>
    </div>
  <% end %>
</div>

app/views/posts/_search_form.html.erb
<div class="container">
  <div class="row d-flex justify-content-center search-form">
    <div class="col-12">
      <div class="d-flex justify-content-center me-3 mb-5">
        <h2 class="text-header2 text-center">
          คุณกำลังมองหาอะไร
        </h2>
        <div class="ms-5 align-self-end pb-4">
          <div class="dot-typing"></div>
        </div>
      </div>
      <div class="box-search" data-controller="my-posts">
        <%= search_form_for @q, url: root_path, data: {controller: "autocomplete", autocomplete_url_value: autocomplete_posts_path } do |f| %>
          <div class="row">
            <div class="col box-search-item has-search">
              <span class="fa fa-search form-control-feedback"></span>
              <%= f.search_field :name_cont, data: { autocomplete_target: "input" }, class: "form-control", placeholder: 'ค้นหาที่นี่' %>
              <div class="result-search">
                <ul class="list-group" data-autocomplete-target="results"></ul>
              </div>
            </div>
            <div class="col-12 col-md-auto mt-3 mt-md-0" id="button-search" >
              <%= f.submit 'ค้นหา', class: "btn btn--secondary w-100" %>
            </div>
          </div>
        <% end %>

        <p class="text-decoration-underline mt-4 pointer mb-0" data-bs-toggle="collapse" data-bs-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample" data-controller="search-form" data-action="click->search-form#checkReset">ค้นหาขั้นสูงและฟิลเตอร์</p>

        <%= search_form_for @q || Post.ransack, url: search_posts_path,
          html: { id: 'searchForm', class: 'form-inline', method: :get },
          data: {
            controller: "search-form autocomplete maps",
            autocomplete_url_value: autocomplete_posts_path
          } do |f| %>

          <%= hidden_field_tag :lat, @lat, data: { maps_target: "latitude", search_form_target: 'latitude' } %>
          <%= hidden_field_tag :lng, @lng, data: { maps_target: "longitude", search_form_target: 'longitude' } %>
          <%= hidden_field_tag :location, @location, data: { maps_target: "address", search_form_target: 'address' } %>

          <div class="collapse" id="collapseExample">
            <br>
            <hr>
            <div class="alert alert-danger d-none" id="categoriesAlert">กรุณาเลือกประเภท</div>
            <div class="row mt-5">
              <div class="col-lg-2 col-xl-1 d-flex align-items-center">
                <p class="mb-0 font-weight600">ประเภท :</p>
              </div>
              <div class="col-md-auto col-lg-5 col-xl-3">
                <label class="cursor-pointer w-100">
                  <div class="checkboxitem" id="check-box-search-lost-category">
                    <%= radio_button_tag('q[category_eq_any][]', 1, @q.category_eq_any&.include?(1) || false, class: 'checkmark-category', data: { search_form_target: 'lostCheckbox', action: 'click->search-form#addCheckboxColor' }, checked: 'checked') %>
                    <i class="fa-solid fa-circle-dot"></i>
                    <i class="fa-thin fa-circle"></i>
                    โพสต์หาของหาย
                  </div>
                </label>
              </div>
              <div class="col-md-auto col-lg-5 col-xl-3 mt-5 mt-md-0">
                <label class="cursor-pointer w-100">
                  <div class="checkboxitem" id="check-box-search-found-category">
                    <%= radio_button_tag('q[category_eq_any][]', 0, @q.category_eq_any&.include?(0)  || false, class: 'checkmark-category', data: { search_form_target: 'foundCheckbox', action: 'click->search-form#addCheckboxColor' }) %>
                    <i class="fa-solid fa-circle-dot"></i>
                    <i class="fa-thin fa-circle"></i>
                     โพสต์ตามหาเจ้าของ
                  </div>
                </label>
              </div>
            </div>

            <div class="row mt-5">
              <div class="col-lg-2 col-xl-1 d-flex align-items-center">
                <%= f.label "ค้นหา :", class: 'font-weight600'%>
              </div>
              <div class="col-lg-10 col-xl-9">
                <%= f.search_field :name_cont, data: {autocomplete_target: "input", search_form_target: 'searchInput', action: 'keyup->search-form#checkSearchorType' }, class: 'form-control ', id: 'name-advance-search', placeholder: 'ค้นหาที่นี่' %>
                <div class="result-search">
                  <ul class="list-group" data-autocomplete-target="results"></ul>
                </div>
              </div>
            </div>

            <div class="row">
              <div class="col-lg-2 col-xl-1 d-flex"></div>
              <div class="col-lg-10 col-xl-9">
                <p class="text-danger pt-2 d-none" id="name-error">กรุณากรอกข้อมูลคำค้นหา หรือ หมวดหมู่</p>
              </div>
            </div>

            <div class="row mt-5">
              <div class="col-lg-2 col-xl-1 d-flex align-items-center">
                <%= f.label "หมวดหมู่ :", class: 'font-weight600'%>
              </div>
              <div class="col-lg-4 col-xl-4">
                <%= f.select :type_id_eq, Type.all.map{ |l| [l.type_name, l.id] }, {:include_blank => 'เลือก'}, class: 'form-control form-select cursor-pointer', id: 'category-advance-search', data: { search_form_target: 'typeSelect', action: 'input->search-form#checkSearchorType' } %>
              </div>
            </div>

            <div class="row">
              <div class="col-lg-2 col-xl-1 d-flex"></div>
              <div class="col-lg-10 col-xl-9">
                <p class="text-danger pt-2 d-none" id="category-error">กรุณากรอกข้อมูลคำค้นหา หรือ หมวดหมู่</p>
              </div>
            </div>

            <div class="row mt-5">
              <div class="col-lg-2 col-xl-1 d-flex align-items-center">
                <%= f.label "วันที่เริ่มต้น :", class: 'font-weight600'%>
              </div>
              <div class="col-lg-4 mb-2">
                <%= f.date_field :date_gteq, class: 'form-control', id: 'start_date', data: { search_form_target: 'startDate', action: 'input->search-form#checkDateStart input->search-form#dateStartSelected' }, max: Date.today %>
                <p class="text-danger t-floating pt-2 d-none" id="date-start-error" style="position: absolute; margin-top: 5px;">ไม่ควรเลือกวันที่เกินปัจจุบัน</p>
              </div>
              <div class="col-auto d-flex mt-5 mt-lg-0 align-items-center">
                <%= f.label "วันที่สิ้นสุด :", class: 'font-weight600'%>
              </div>
              <div class="col-lg-4 mb-2">
                <%= f.date_field :date_lteq, class: 'form-control', id: 'end_date', data: { search_form_target: 'endDate', action: 'input->search-form#checkDateEnd input->search-form#dateEndSelected' }, max: Date.today %>
                <p class="text-danger t-floating pt-2 d-none" id="date-end-error" style="position: absolute; margin-top: 5px;">ไม่ควรเลือกวันที่เกินปัจจุบัน</p>
              </div>
            </div>

            <div class="row" style="margin-top: 60px;">
              <div class="col-lg-2 col-xl-1 d-flex align-items-center">
                <%= f.label "สถานที่ :", class: 'font-weight600'%>
              </div>
              <div class="col-lg-10 col-xl-9">
                <%= text_field :map, :field, value: @location, placeholder: "Search", class: 'form-control location-advance',  id: 'location-advance-search', data: { maps_target: "field", search_form_target: 'place', action: "keydown->maps#preventSubmit input->search-form#checkLocationField input->maps#removeMarker input->search-form#checkLocation" } %>
                <i class="fa fa-search form-control-feedback location"></i>
              </div>
            </div>

            <div class="row">
              <div class="col-lg-2 col-xl-1 d-flex"></div>
              <div class="col-lg-10 col-xl-9">
                <p class="text-danger pt-2 d-none" id="location-error">กรุณาเลือกสถานที่</p>
              </div>
            </div>

            <div class="row mt-5">
              <div class="col-lg-2 col-xl-1 d-flex">
              </div>
              <div class="col-lg-10 col-xl-11">
                <%= content_tag :div, nil, data: { action: 'google-maps-callback@window->maps#initializeMap click->search-form#checkMarker', maps_target: "map", search_form_target: 'place'}, class: 'map advance' %>
              </div>
            </div>

            <div class="pt-5"></div>
            <div class="d-md-flex mt-5">
              <div class="flex-grow-1 d-flex">
                <%= button_tag type: 'button', data: { action: 'click->search-form#clearForm click->maps#removeMarkerOnClick' }, class: 'btn' do %>
                  <i class="fa-solid fa-arrow-rotate-left me-3"></i> ล้างข้อมูล
                <% end %>
                </div>
              <div class="me-md-3 d-grid mt-5 mt-md-0"><%= link_to "ยกเลิก", :back, class: "btn btn--outline-secondary", data: { bs_toggle: 'collapse', bs_target: '#collapseExample' } %></div>
              <div class="d-grid mt-5 mt-md-0"><%= f.submit "ตกลง", class: "btn btn--primary", data: { action: 'search-form#validateForm' } %></div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/posts/autocomplete.html.erb
<% @search_results.each do |result| %>
  <li calss="list-group-item" role="option">
    <i class="fa fa-search"></i>
    <div class="result-autocomplete"><%= result %></div>
  </li>
<% end %>

app/views/posts/lost.html.erb
<%= render 'posts/search_form' %>
<div class="lost-listposts mt-14">
  <div class="container pt-5">
    <div class="row justify-content-between align-items-center mb-5">
      <% if @tab == 'my_post' %>
        <div class="col-md-auto order-md-last mb-5 mb-md-0">
          <div class="btn btn--primary-posts btn--w-100" id="button-create-post" >
            <i class='fas fa-plus-circle'></i>
            <%= link_to "สร้างโพสต์", category_selects_posts_path %>
          </div>
        </div>

        <div class="col-md-5">
          <ul class="tabs btn--w-100 mb-0">
            <li class="tab-item">
              <%= link_to 'รายการทั้งหมด', root_path , class: "btn btn--outline-secondary tab-link" %>
            </li>
            <li class="tab-item">
              <%= link_to 'รายการของฉัน', lost_posts_path(tab: 'my_post'), class: "btn btn--secondary tab-link" %>
            </li>
          </ul>
        </div>
      </div>
    <% end %>
    <% if params[:q].present? %>
      <div class="row justify-content-start align-items-center mb-5">
        <div class="col">
          <div class="text-result-search">ผลลัพธ์การค้นหา</div>
          <hr class="style">
          <div class="search-value">
            <p class="text-body font-weight600">ค้นหา :</p>
            <div class="result-tag bg-color--primary200"> <%= params[:q][:name_cont] %></div>
          </div>
        </div>
      </div>
    <% end %>
    <%= form_with(url: lost_posts_path, method: :get, id: 'homeFilter') do |f| %>
      <div class="row mt-5">
        <%= hidden_field_tag 'tab', @tab %>
        <h4 class="col-auto">รายการโพสต์ตามหาของทั้งหมด(<%= @posts.total_count %>)</h4>
        <div class="col-md-5">
          <% if @tab == 'my_post' %>
            <%= render 'filter', f:, filter: @filter, category: 'lost_item' %>
          <% end %>
        </div>
        <br>
        <% if @posts.present? %>
          <div class="row row-cols-1 row-cols-md-4 g-4">
            <%= render 'posts/card_content', posts: @losts, category: 'lost_item', tab: @tab, filter: @filter, f:  %>
          </div>
        <% else %>
          <div class="empty-result">
            <div class="bell-item">
              <i class="fa-regular fa-bell-on"></i>
              <p class="text-result">ไม่มีรายการแสดง</p>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
  <div style="margin-top: 4rem;">
    <%= paginate @posts %>
    <br>
  </div>
</div>

app/views/posts/new.html.erb
<div class="container">
  <div class="row ">
    <div class="row justify-content-md">
      <div class="fs-2 col col-lg-2">
        <%= link_to(category_selects_posts_path, class: 'text-decoration-none', id: 'back-category-link') do %>
          <i class="fa-solid fa-arrow-left"></i> ย้อนกลับ
        <% end %>
      </div>
    </div>
  </div>
  <br>
  <div class="mb-4 bg-body card-form padding-box">
    <h4 class="mb-0" id="form-create-tile">สร้างโพสต์<%= @post.lost_item? ? 'ตามหาของหาย' : 'ตามหาเจ้าของ' %></h4>
    <hr class="underline-title">
    <%= render 'form', post: @post %>
  </div>
</div>