config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#index'
  get 'changelog', to: 'home#changelog'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations'
  }

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  namespace :users do
    resources :settings, only: [] do
      collection do
        get 'password/edit', to: 'settings#edit_password'
        put 'password'
      end
    end
  end

  resources :posts, only: %i[new show edit create update destroy] do
    resources :comments, only: %i[create]

    resources :posters, only: %i[new] do
      collection do
        get :show
      end
    end

    collection do
      get :autocomplete
      get :lost
      get :found
      get :category_selects

      get :search
    end
  end

  resources :places do
    collection do
      get :search
    end
  end

  resources :notifications, only: %i[index]
end

app/models/place.rb
# frozen_string_literal: true

class Place < ApplicationRecord
end

app/controllers/places_controller.rb
# frozen_string_literal: true

class PlacesController < ApplicationController
  before_action :search_map, only: %i[index]
  before_action :load_places, only: %i[index]
  before_action :set_place, only: %i[show edit update destroy]

  def index; end

  def show; end

  def new
    @place = Place.new
  end

  def edit; end

  def create
    @place = Place.new(place_params)

    if @place.save
      redirect_to place_url(@place), notice: 'Place was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @place.update(place_params)
      redirect_to place_url(@place), notice: 'Place was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    if @place.destroy
      redirect_to places_url, notice: 'Place was successfully destroyed.'
    else
      render :show, status: :unprocessable_entity
    end
  end

  def search; end

  private

  def load_places
    @places ||= Place.all
  end

  def search_map
    return unless params[:search] && params[:search][:latitude].present? && params[:search][:longitude].present?

    latitude = (params[:search][:latitude].to_d - 1)..(params[:search][:latitude].to_d + 1)
    longitude = (params[:search][:longitude].to_d - 1)..(params[:search][:longitude].to_d + 1)

    @places = Place.where(latitude:, longitude:)
  end

  def set_place
    @place = Place.find(params[:id])
  end

  def place_params
    params.require(:place).permit(:name, :latitude, :longitude)
  end
end

app/views/places/_form.html.erb
<div data-controller="maps" data-action="google-maps-callback@window->maps#initializeMap">
  <%= simple_form_for(@place) do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

    <div class="form-inputs">
      <%= f.input :search, input_html: { data: { maps_target: "field", action: "keydown->maps#preventSubmit" }, value: '' } %>
      <%= f.input :name, input_html: { data: { maps_target: "address" } } %>
      <%= f.input :latitude, input_html: { data: { maps_target: "latitude" } } %>
      <%= f.input :longitude, input_html: { data: { maps_target: "longitude" } } %>
    </div>

    <%= content_tag :div, nil, data: { maps_target: "map" }, class: 'map' %>

    <div class="form-actions">
      <%= f.button :submit %>
    </div>
  <% end %>
</div>

app/views/places/_place.html.erb
<div id="<%= dom_id place %>">
  <p>
    <strong>Name:</strong>
    <%= place.name %>
  </p>

  <p>
    <strong>Latitude:</strong>
    <%= place.latitude %>
  </p>

  <p>
    <strong>Longitude:</strong>
    <%= place.longitude %>
  </p>
</div>

app/views/places/edit.html.erb
<h1>Editing place</h1>

<%= render "form", place: @place %>

<br>

<div>
  <%= link_to "Show this place", @place %> |
  <%= link_to "Back to places", places_path %>
</div>

app/views/places/index.html.erb
<p style="color: green"><%= notice %></p>

<%= link_to 'Search page', search_places_path %>

<h1>Places</h1>

<div id="places">
  <% @places.each do |place| %>
    <%= render place %>
    <p>
      <%= link_to "Show this place", place %>
    </p>
  <% end %>
</div>

<%= link_to "New place", new_place_path %>

app/views/places/new.html.erb
<h1>New place</h1>

<%= render "form", place: @place %>

<br>

<div>
  <%= link_to "Back to places", places_path %>
</div>

app/views/places/search.html.erb
<h1>search</h1>

<div data-controller="search-posts" data-action="google-maps-callback@window->search-posts#initializeMap">
  <%= simple_form_for :search, method: :get, url: places_path do |f| %>
    <h1>สถานที่ <%= button_tag '+', type: 'button', data: { action: "click->search-posts#setContentMap" } %></h1>

    <div style="display: none;" data-search-posts-target="mapDisplay">
      <div class="form-inputs">
        <%= f.input :search, input_html: { name: '', data: { search_posts_target: "field", action: "keydown->search-posts#preventSubmit" } } %>
        <span data-search-posts-target="address"></span>
        <%= hidden_field_tag 'search[latitude]', '', data: { search_posts_target: "latitude" } %>
        <%= hidden_field_tag 'search[longitude]', '', data: { search_posts_target: "longitude" } %>
      </div>

      <%= content_tag :div, nil, data: { search_posts_target: "map" }, class: 'map' %>
    </div>

    <div class="form-actions">
      <%= f.button :submit, 'Search' %>
    </div>
  <% end %>
</div>

app/views/places/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @place %>
<%= image_tag "https://maps.googleapis.com/maps/api/staticmap?markers=color:red%7C#{@place.latitude},#{@place.longitude}&zoom=18&size=400x300&center=#{@place.latitude},#{@place.longitude}&key=#{ENV['MAPS_API_KEY']}", alt: "Map" %>

<div>
  <%= link_to "Edit this place", edit_place_path(@place) %> |
  <%= link_to "Back to places", places_path %>

  <%= button_to "Destroy this place", @place, method: :delete %>
</div>