config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#index'
  get 'changelog', to: 'home#changelog'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations'
  }

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  namespace :users do
    resources :settings, only: [] do
      collection do
        get 'password/edit', to: 'settings#edit_password'
        put 'password'
      end
    end
  end

  resources :posts, only: %i[new show edit create update destroy] do
    resources :comments, only: %i[create]

    resources :posters, only: %i[new] do
      collection do
        get :show
      end
    end

    collection do
      get :autocomplete
      get :lost
      get :found
      get :category_selects

      get :search
    end
  end

  resources :places do
    collection do
      get :search
    end
  end

  resources :notifications, only: %i[index]
end

app/views/layouts/_footer.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-4 col-md-2 col-lg-1">
      <%= image_tag 'logo-footer.png', class: 'img-fluid', alt: '' %>
    </div>
    <div class="col-md-4 col-lg-5 mt-5 mt-md-0">
      <h4>Lost n Found</h4>
      <p class="mt-4">
        เว็ปไซต์ที่เราจะช่วยคุณเพิ่มช่องทางในการตามหาสิ่งของที่คุณทำหาย
        <br>และตามหาเจ้าของ เพื่อสร้างสังคมที่ดีขึ้น  ถ้าคุณหาของไม่เจอ ให้เราช่วยหา
      </p>
    </div>
    <div class="col-md-2 mt-5 px-0" id="footer-link">
      <%= link_to root_path, class: 'nav-link text-underline', id: 'footer-root-path-link' do %> หน้าแรก <% end %>
      <%= link_to lost_posts_path, class: 'nav-link text-underline', id: 'footer-lost-posts-path-link' do %> รายการตามหาของหาย <% end %>
      <%= link_to found_posts_path, class: 'nav-link text-underline', id: 'footer-found-posts-path-link' do %> รายการตามหาเจ้าของ <% end %>
      <% if !user_signed_in? %><%= link_to new_user_session_path, class: 'nav-link text-underline', id: 'footer-login-link' do %> Login <% end %><% end %>
    </div>
    <div class="col-md-4 mt-5">
      <div class="row">
        <div class="col-lg-6">
          <div class="d-flex mb-3">
            <div class="me-2"><i class="fa-brands fa-facebook fa-xl"></i></div>
            <div><%= link_to 'Lost n Found', '', class: 'nav-link p-0' %> </div>
          </div>
          <div class="d-flex mb-3">
            <div class="me-2"><i class="fa-solid fa-envelope fa-xl"></i></div>
            <div><%= mail_to 'lostnfound@bananacoding.com', 'lostnfound@bananacoding.com', class: 'nav-link p-0' %></div>
          </div>
          <div class="d-flex">
            <div class="me-2"><i class="fa-solid fa-phone fa-xl mt-4"></i></div>
            <%= phone_to '053-020078', class: 'nav-link p-0 mt-2' %>
          </div>
        </div>
        <div class="col-lg-6 mt-4 mt-lg-0">
        </div>
      </div>
    </div>
    <hr class="mt-5">
    <div class="text-center">
      <p>@ lostnfound All right reserved | v. <%= File.read("VERSION") %></p>
    </div>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<button class="btn navbar-mobile" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasRight" aria-controls="offcanvasRight">
  <i class="fa-solid fa-bars fa-2xl"></i>
</button>

<div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasRight" aria-labelledby="offcanvasRightLabel">
  <div class="offcanvas-header">
    <h5 class="offcanvas-title" id="offcanvasRightLabel"></h5>
    <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
  </div>
  <div class="offcanvas-body">
    <ul class="navbar-nav ms-auto mb-2 mb-lg-0 d-flex align-items-lg-center">
      <li class="nav-item ms-lg-3 mt-4 mt-xl-0">
        <%= link_to 'หน้าแรก', root_path, class: 'nav-link color--secondary', id: 'nav-root-path-link'%>
      </li>

      <li class="nav-item ms-lg-3 mt-4 mt-xl-0">
        <%= link_to 'รายการตามหาของหาย', lost_posts_path, class: 'nav-link color--secondary', id: 'nav-lost-posts-path-link' %>
      </li>

      <li class="nav-item ms-lg-3 mt-4 mt-xl-0">
        <%= link_to 'รายการตามหาเจ้าของ', found_posts_path, class: 'nav-link color--secondary', id: 'nav-found-posts-path-link' %>
      </li>

      <% if  user_signed_in? %>
        <li class="nav-item ms-lg-3 mt-4 mt-xl-0 mr-30">
          <div class="dropdown" id="dropdown-nav" >
            <a class="nav-link link-dark border border-1 border-dark rounded-5 padding-12" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
                <% if current_user.avatar.attached? %>
                  <div class="d-flex">
                    <%= image_tag(current_user.avatar, class: "rounded-circle profile-navbar mr-1") %>
                    <div class="flex-grow-1 align-self-center mr-2">
                      <%= current_user.username %>
                    </div>
                    <div class="align-self-center"><i class='fas fa-chevron-down'></i></div>
                  </div>
                <% else %>
                  <div class="d-flex">
                    <img alt="image" class="rounded-circle profile-navbar mr-1" src="https://media.istockphoto.com/vectors/default-profile-picture-avatar-photo-placeholder-vector-illustration-vector-id1223671392?k=20&m=1223671392&s=612x612&w=0&h=lGpj2vWAI3WUT1JeJWm1PRoHT3V15_1pdcTn2szdwQ0="
                  >
                    <div class="flex-grow-1 align-self-center mr-2">
                      <%= current_user.username %>
                    </div>
                    <div class="align-self-center"><i class='fas fa-chevron-down'></i></div>
                  </div>
                <% end %>
            </a>
            <ul class="dropdown-menu dropdown-min-width-1 border border-1 border-dark rounded-5 " aria-labelledby="dropdownMenuLink">
              <li>
                <%= link_to 'โปรไฟล์ของฉัน', edit_user_registration_path, class: 'dropdown-item', id: 'nav-edit-profile-link' %>
              </li>
              <li>
                <%= link_to 'ออกจากระบบ', destroy_user_session_path, method: :delete, class: 'dropdown-item', id: 'nav-logout-link' %>
              </li>
            </ul>
          </div>
        </li>

        <li class="nav-item mt-4 mt-xl-0">
          <%= render 'layouts/notification', id: 'nav-dropdown-notification' %>
          <%= link_to 'ดูการแจ้งเตือนทั้งหมด', notifications_path, class: 'nav-link color--secondary', id: 'nav-noti-path-link' %>
        </li>
      <% else %>
        <li class="nav-item ms-lg-3 mt-4 mt-xl-0">
          <%= link_to 'เข้าสู่ระบบ', new_user_session_path, class: 'btn btn--outline-secondary', id: 'nav-login-link' %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/layouts/_navbar_origin.html.erb
<nav class="navbar navbar-expand-lg">
  <div class="container px-md-0">
    <a class="navbar-brand" href="/" id="home-logo-app">
      <%= image_tag 'logo_nav.png', alt: '' %>
    </a>
    <%= render 'layouts/navbar' %>
  </div>
</nav>

app/views/layouts/_navbar_white.html.erb
<nav class="navbar navbar-expand-lg">
  <div class="container px-md-0">
    <a class="navbar-brand" href="/" id="home-logo-app">
      <%= image_tag 'logo-color.svg', alt: '' %>
    </a>

    <button class="navbar-toggler p-2" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <i class="fa-solid fa-bars fa-2xl"></i>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0 d-flex align-items-lg-center">
        <li class="nav-item ms-lg-3 mt-4 mt-xl-0">
          <%= link_to 'หน้าแรก', root_path, class: 'nav-link color--secondary', id: 'nav-root-path-link'%>
        </li>

        <li class="nav-item ms-lg-3 mt-4 mt-xl-0">
          <%= link_to 'รายการตามหาของ', lost_posts_path, class: 'nav-link color--secondary', id: 'nav-lost-posts-path-link' %>
        </li>

        <li class="nav-item ms-lg-3 mt-4 mt-xl-0">
          <%= link_to 'รายการตามหาเจ้าของ', found_posts_path, class: 'nav-link color--secondary', id: 'nav-found-posts-path-link' %>
        </li>

        <% if  user_signed_in? %>
          <li class="nav-item ms-lg-3 mt-4 mt-xl-0 mr-30">
            <div class="dropdown" id="dropdown-nav" >
              <a class="nav-link link-dark border border-1 border-dark rounded-5 padding-12" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
                <% if current_user.avatar.attached? %>
                <%= image_tag(current_user.avatar, class: "rounded-circle profile-navbar") %>&Tab;<%= current_user.username %>&nbsp;&nbsp;<i class='fas fa-chevron-down'></i>
                <% else %>
                <img alt="image" class="rounded-circle profile-navbar" src="https://media.istockphoto.com/vectors/default-profile-picture-avatar-photo-placeholder-vector-illustration-vector-id1223671392?k=20&m=1223671392&s=612x612&w=0&h=lGpj2vWAI3WUT1JeJWm1PRoHT3V15_1pdcTn2szdwQ0="
                >&Tab;<%= current_user.username %>&nbsp;&nbsp;<i class='fas fa-chevron-down'></i>
                <% end %>
              </a>
              <ul class="dropdown-menu dropdown-min-width-1 border border-1 border-dark rounded-5 " aria-labelledby="dropdownMenuLink">
                <li>
                  <%= link_to 'โปรไฟล์ของฉัน', edit_user_registration_path, class: 'dropdown-item', id: 'nav-edit-profile-link' %>
                </li>
                <li>
                  <%= link_to 'ออกจากระบบ', destroy_user_session_path, method: :delete, class: 'dropdown-item', id: 'nav-logout-link' %>
                </li>
              </ul>
            </div>
          </li>

          <li class="nav-item mt-4 mt-xl-0">
            <%= render 'layouts/notification', id: 'nav-dropdown-notification' %>
          </li>
        <% else %>
          <li class="nav-item ms-lg-3 mt-4 mt-xl-0">
            <%= link_to 'เข้าสู่ระบบ', new_user_session_path, class: 'btn btn--outline-secondary', id: 'nav-login-link' %>
          </li>
          <!--<li class="nav-item ms-lg-3 mt-4 mt-xl-0 mt-3 mt-md-0">
            <button class="btn btn--outline-primary">
              <%= link_to new_user_registration_path, class: 'nav-link p-0' do %> สมัครสมาชิก <% end %>
            </button>
          </li>-->
        <% end %>

        <!--
        <li class="nav-item dropdown ms-lg-3 mt-4 mt-xl-0">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <%= image_tag 'Thai.png', alt: '', class: 'icon-l' %>
          </a>
          <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
            <li class="p-3">
              <%= image_tag 'Thai.png', alt: '', class: 'icon-l' %> Thai
            </li>
            <li class="p-3">
              <%= image_tag 'Eng.png', alt: '', class: 'icon-l' %> English
            </li>
          </ul>
        </li>
        -->
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_notification.html.erb
<%= turbo_stream_from dom_id(current_user,:notification)  %>

<div class="dropdown notification-dropdown">
  <button id="dropdownNotification" type="button" class="btn btn-default px-0 px-lg-auto border-0"
    data-bs-toggle="dropdown" data-bs-auto-close="outside" aria-expanded="false">
    <div class="d-inline-flex position-relative light">
      <div class="d-inline-flex position-relative">
          <i class="fas fa-bell" style="font-size: 24px"></i>
          <%= render 'notifications/count', count: current_user.notifications.unread.count %>
      </div>
    </div>
  </button>

  <div id="notifications" class="dropdown-menu dropdown-caret dropdown-size" aria-labelledby="dropdownNotification">
    <%= render 'notifications/notifications',
      notifications: current_user.notifications.latest_with_limit,
      unread_notifications: current_user.notifications.unread_latest_with_limit %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LostItem</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= favicon_link_tag 'logo-color.svg' %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= yield :meta %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?key=#{Figaro.env.MAPS_API_KEY}&libraries=places&callback=dispatchMapsEvent",
      defer: true,
      data: { turbo_eval: false } %>
    <%= javascript_include_tag 'https://kit.fontawesome.com/70f81e00e8.js',
      crossorigin: 'anonymous',
      defer: true,
      data: { turbo_eval: false } %>
  </head>

  <body class="background">
    <header>
      <%= render 'layouts/navbar_origin' %>
    </header>

    <main>
      <%= yield %>
    </main>

    <footer class="footer container-fluid p-0">
      <%= render 'layouts/footer' %>
    </footer>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LostItem</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= favicon_link_tag 'logo-color.svg' %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= yield :meta %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?key=#{Figaro.env.MAPS_API_KEY}&libraries=places&callback=dispatchMapsEvent",
      defer: true,
      data: { turbo_eval: false } %>
    <%= javascript_include_tag 'https://kit.fontawesome.com/70f81e00e8.js',
      crossorigin: 'anonymous',
      defer: true,
      data: { turbo_eval: false } %>
  </head>

  <body class="background">

    <main>
      <%= yield %>
    </main>
    
  </body>
</html>

app/views/layouts/devise_sign_in.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LostItem</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= favicon_link_tag 'logo-color.svg' %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= yield :meta %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?key=#{Figaro.env.MAPS_API_KEY}&libraries=places&callback=dispatchMapsEvent",
      defer: true,
      data: { turbo_eval: false } %>
    <%= javascript_include_tag 'https://kit.fontawesome.com/70f81e00e8.js',
      crossorigin: 'anonymous',
      defer: true,
      data: { turbo_eval: false } %>
  </head>

  <body>
    <header class="nav-white">
      <%= render 'layouts/navbar_white' %>
    </header>

    <main>
      <%= yield %>
    </main>

    <footer class="footer container-fluid p-0">
      <%= render 'layouts/footer' %>
    </footer>
  </body>
</html>

app/views/layouts/nav_white.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LostItem</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= favicon_link_tag 'logo-color.svg' %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= yield :meta %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?key=#{Figaro.env.MAPS_API_KEY}&libraries=places&callback=dispatchMapsEvent",
      defer: true,
      data: { turbo_eval: false } %>
    <%= javascript_include_tag 'https://kit.fontawesome.com/70f81e00e8.js',
      crossorigin: 'anonymous',
      defer: true,
      data: { turbo_eval: false } %>
  </head>

  <body>
    <header class="nav-white">
      <%= render 'layouts/navbar_white' %>
    </header>

    <main>
      <%= yield %>
    </main>

    <footer class="footer container-fluid p-0">
      <%= render 'layouts/footer' %>
    </footer>
  </body>
</html>

app/views/layouts/nav_white_without_footer.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LostItem</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= favicon_link_tag 'logo-color.svg' %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= yield :meta %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?key=#{Figaro.env.MAPS_API_KEY}&libraries=places&callback=dispatchMapsEvent",
      defer: true,
      data: { turbo_eval: false } %>
    <%= javascript_include_tag 'https://kit.fontawesome.com/70f81e00e8.js',
      crossorigin: 'anonymous',
      defer: true,
      data: { turbo_eval: false } %>
  </head>

  <body>
    <header class="nav-white">
      <%= render 'layouts/navbar_white' %>
    </header>

    <main>
      <%= yield %>
    </main>
  </body>
</html>

app/views/layouts/pdf.pdf.erb
<!doctype html>
<html>
  <head>
    <meta charset='utf-8' />
    <link href='https://fonts.googleapis.com/css2?family=Prompt:wght@100;200;300;400;500;600;700;800&display=swap' rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/js/all.min.js" integrity="sha512-6PM0qYu5KExuNcKt5bURAoT6KCThUmHRewN3zUFNaoI6Di7XJPTMoT6K0nsagZKk2OB4L7E3q1uQKHNHd4stIQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.slim.min.js" integrity="sha256-u7e5khyithlIdTpu22PHhENmPcRdFiHRjhAuHcs05RI=" crossorigin="anonymous"></script>
    <script src="https://unpkg.com/dayjs@1.8.21/dayjs.min.js"></script>
    <script src="https://unpkg.com/dayjs@1.8.21/locale/th.js"></script>

    <style>
      .printable {
        font-family: 'Prompt';
        background-color: white;
      }

      .printhead {
        width: 100%;
        text-align: center;
        background-color: #D10026;
        height: 150px;
        padding: 0;
        margin:0;
      }

      .borderhead {
        position: absolute;
        background-color: #D10026;
        width: 100%;
        height: 150px;
        top: 0;
        z-index: -1;
        left: 0;
      }

      .printbody {
        padding: 30px;
        height: 262mm;

      }

      .printfoot {
        padding: 0 50px;
        width: 90%;
        margin: auto;

      }

      .hrcontact {
        padding-top: 2px;
        border: none;
        background-color: black;
        margin-top: 50px;
        margin-left: 50px;
        margin-right: 160px;

      }

      .extra {
        z-index: 10;
        position: absolute;
        margin-top: -175px;
        width: 100%;
        height: 200px ;
      }

      .qr-code {
        z-index: 10;
        position: fixed;
        margin-left: 830px;
        margin-top: 40px;
        svg {
          width: 120px;
          height: 120px;
        }
      }

      .scan {
        z-index: 20;
        position: fixed;
        margin-top: 155px;
        margin-left: 865px;
      }

      .title{
        font-size: 100px;
        color: white;
        text-align: center;
      }

      .name {
        text-align: center;
        font-size: 40px;
        margin-bottom: 0;

      }

      .data {
        font-size: 20px;
        text-align: center;
        word-wrap: break-word;
      }

      .address{
        word-wrap: break-word;
      }

      .image {
        width: 100%;
        height:550px;
        background-size: cover;
        background-position: center center;
        background-repeat: no-repeat;
        background-image: url('<%= @p["images"] %>');
      }

    </style>

    <script>
      $(function() {
        $('*[data-datetime]').each(function(index, elem) {
          const $elem = $(elem);
          const dateStr = $elem.data('datetime');
          $elem.html(dayjs().locale('th').format('DD MMMM YYYY'));
        })
      })
    </script>

  </head>
  <body>
    <main>
      <%= yield %>
    </main>
  </body>
</html>